### ISSUE TITLE
issue today in fetching

### ISSUE THREAD

**Issue by tsailipu** [kirbyt/appdailysales#3]
Did iTunes Connect change again?

**Comment by kirbyt** [comment]
I'm traveling at the moment, so I don't know. I'll take a look Sunday when I return home.

Also, make sure you have agreed to the latest agreements in iTC. You can do this by signing into iTC from your browser and see if it prompts you about new agreements. 

-KIRBY

**Comment by codetiger** [comment]
We too have the same problem. And there is no contract pending...

**Comment by kirbyt** [comment]
Thanks for letting me know. I'll take a look when I return on Sunday.

-KIRBY

**Comment by codetiger** [comment]
Just for your information, I guess the Notification about delay in report on top of the itunesconnect page is the culprit. I'll try to fix it if possible and let you know. Am not a pro in page scrapping by the way. :)

**Comment by kirbyt** [comment]
It seems a minor change was made to iTC. I have fixed the script. Let me know if you are still having problems. Thanks.

-KIRBY

**Comment by zzzjim** [comment]
It appears to be downloading the weekly report.

dateListAvailableDays:  ['10/15/2011', '10/14/2011', '10/13/2011', '10/12/2011', '10/11/2011', '10/10/2011', '10/09/2011', '10/08/2011', '10/07/2011', '10/06/2011', '10/05/2011', '10/04/2011', '10/03/2011', '10/02/2011']
dateListAvailableWeeks:  ['10/09/2011', '10/02/2011', '09/25/2011', '09/18/2011', '09/11/2011', '09/04/2011', '08/28/2011', '08/21/2011', '08/14/2011', '08/07/2011', '07/31/2011', '07/24/2011', '07/17/2011']
reportDates:  [datetime.date(2011, 10, 15), datetime.date(2011, 10, 14), datetime.date(2011, 10, 13), datetime.date(2011, 10, 12), datetime.date(2011, 10, 11), datetime.date(2011, 10, 10), datetime.date(2011, 10, 9)]
Downloading daily sales reports.
Downloading report for:  10/15/2011
Server: Apache-Coyote/1.1
X-Powered-By: JSF/1.2
Content-Encoding: agzip
Content-Disposition: attachment;filename=S_W_80071726_20111009_20111017053806617.txt.gz
filename: S_W_80071726_20111009_20111017053806617.txt.gz
Content-Type: application/a-gzip;charset=ISO-8859-1
Content-Length: 1881
Date: Mon, 17 Oct 2011 05:38:09 GMT

Unzipping archive file:  S_W_80071726_20111009_20111017053806617.txt.gz
Saving download file: ./daily/S_W_80071726_20111009_20111017053806617.txt

**Comment by tsailipu** [comment]
Yeap, same problem observed.  It's downloading from 10/03 to 10/09 for example, when I run it without -D option.

**Comment by aleban** [comment]
I can confirm that.
I'm trying to download the latest 14 days, but seem to recieve the latest weekly report (13 identical files)

**Comment by kirbyt** [comment]
Oh crap. That's what I get for trying to make a quick change in between trips. Sorry folks.

-KIRBY

**Comment by kirbyt** [comment]
Okay, should be fixed now. Sorry for the slip up in the previous commit.

-KIRBY

**Comment by loayjo** [comment]
Guys,
if kirbyt allow me, change the 39 in these lines to 38:
         match = re.findall('theForm:j_id_jsp_[0-9]*_39', html)
         ajaxName = re.sub('._39', '_2', dailyName)
         dateName = re.sub('._39', '_8', dailyName)
         selectName = re.sub('._39', '_32', dailyName)

**Comment by aleban** [comment]
Thank You very much for the quick fix, Kirby & loayjo, it's working again!

Andrej

**Comment by zauin** [comment]
I can't still get my data...

Error message as follows,

10/18/2011 report is not available - try again later.
10/17/2011 report is not available - try again later.
10/16/2011 report is not available - try again later.
10/15/2011 report is not available - try again later.
10/14/2011 report is not available - try again later.

**Comment by kirbyt** [comment]
I'll take a look once I return. I'm away on holiday this week, and I don't have my computer with me.

-KIRBY

**Comment by zauin** [comment]
Hi kirbyt, 

v2.9.2 is working very well.. 
thank you~

Have a good time..

**Comment by zzzjim** [comment]
seems to be working for me as well.

**Comment by kirbyt** [comment]
Good to hear. I am marking this issue as closed. Thanks all.

-KIRBY

**Comment by tsailipu** [comment]
Hi Kirby,

  Run into fetching issue today.  Retried just now and same problem.  Has something changed again?

  Thanks!
  Philip

**Comment by kirbyt** [comment]
Hi Philip,

I have confirmed that the script is once again broke.  The likely cause is a change to iTC.  I'm not sure if and when I will have time to fix this.  It might be time to retire this script and use another service.  I for one have been using AppFigures for the last year.

-KIRBY

**Comment by tsailipu** [comment]
Got it.  I could help debug and fix as well.  But I am checking out AppFigures - looks pretty decent - esp with API support.  I have a home-grown script that fetches Android Market data daily myself (a year ago, there was no available tools/sites that offer Android support), but AppFigures works with both now, which is great. I put your name as referrer - though it doesn't look like they reward referral in any way yet.  Will try out and see.  Thanks!

**Comment by kirbyt** [comment]
Send me a pull request if you do fix it, and I'll commit it to the master branch.

With services like AppFigures and App Annie, it really is hard to want to work on the script. 

-KIRBY

**Comment by aaarrrggh** [comment]
Hi...

I think I've fixed this for you and have issued a pull request.

I'm not a python developer so I'm not 100% sure... I've confirmed it by getting the file to download some files on certain dates, and that certainly seems to be working.

Could you please take a look at what I've done and just test it a bit to make sure it's all ok? Hopefully it's fixed and good to go :-)

**Comment by kirbyt** [comment]
Thanks aaarrrggh. The fix does indeed work.  I merged the pull request and the script is working again.

-KIRBY

**Comment by tsailipu** [comment]
Just pulled and verified on my end as well.  (I pulled what seems to be an earlier change yesterday, so this change, 2.9.3, didn't come in after this pull).

**Comment by zzzjim** [comment]
The latest 2.9.3 is working for me.
